---
booktitle: Proceedings of the 7th Annual Learning for Dynamics \& Control Conference
title: Proceedings of Machine Learning Research
shortname: L4DC
year: '2025'
volume: '283'
start: &1 2025-06-04
end: 2025-06-06
published: 2025-05-22
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: l4dc2025
month: 0
tex_title: Proceedings of the 7th Annual Learning for Dynamics & Control Conference
cycles: false
bibtex_editor: Ozay, Necmiye and Balzano, Laura and Panagou, Dimitra and Abate, Alessandro
editor:
- given: Necmiye
  family: Ozay
- given: Laura
  family: Balzano
- given: Dimitra
  family: Panagou
- given: Alessandro
  family: Abate
description: |
  Proceedings of the 7th Annual Learning for Dynamics \& Control Conference
    Held in University of Michigan, Ann Arbor, MI, USA on 04-06 June 2025

  Published as Volume 283 by the Proceedings of Machine Learning Research on 22 May 2025.

  Volume Edited by:
    Necmiye Ozay
    Laura Balzano
    Dimitra Panagou
    Alessandro Abate

  Series Editors:
    Neil D. Lawrence
date_str: 04--06 Jun
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v283"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v283
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v283
email: ''
conference:
  name: 7th Annual Learning for Dynamics \& Control Conference
  url: https://sites.google.com/umich.edu/l4dc2025/
  location: University of Michigan, Ann Arbor, MI, USA
  dates:
  - *1
  - 2025-06-05
  - 2025-06-06
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: l4dc2025.bib
# Site settings
# Original source:  l4dc2025.bib
